language: java
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.m2"
after_success:
- "./gradlew cobertura coveralls --stacktrace"
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayPublish --stacktrace
env:
  global:
  - secure: Dq5sTTGTGPzgczOOMbaQy/8h1Xjvi0C7twDT1gCHsXOKVGpMIPIBnAM2GuQkqAui/bLRlCwv7xhZ1RByqvXj8MOxGpKhLnGwVrizqYdXAcJXxL3XUC3Zf8XOP5PEQvnQmBC3rmQoXWKBgdditrVH/KWcRm9TF3VrFHqh3O0DX1EFMaPibeVRrO1xTOTDKsJi2DbvghLL6IXSCjkp4umxRqUkEalhLDmo3jnuCcFyTiM/fP0+9gmfaIW0f1+Oq+lkiQzYvI0YYTQINSZBpNgIZVoYkzgZZlSa8Fp0XTlZ5OTfBkecZv+8g6pseOvSYKxyLZVTYQ6nRl1bLS5a4sePHXBa1Y8g43nhIPluDM86wdRCxAzFhiAoQOKnsZ100M4RyPabphi292KtJS2hv6WNONS+nMeBByncLfWuVQAJEx4jeNgKtgdhYD2qVQu2cnQ0/k2dW0p1xNo17UmkQurmQu8OQ10Sn7omDti1vLuK5gvWLtKzDzLxA6rF/xaqceXTMmCyN2BZ+KSM4eZ+C1O/PZCI/E4rYEd2oCnfM/QonGv9UK4fxeP0OuCLsDB+otZbV+0kKdqdMwpsNERvj2GccO6XCvoXtB0sR2T/u5yARcwBPY2yXZPGE8fS9Q8xYMTRJgI8QU5GgURqOWZYQK0BIyLZ6I5yKZbjeEUnSHH/DVE=
  - secure: Af2sspH5mroTmpH01maIV3Ee9+uDCpr6txHJeYnygF2oX6G2oC0/F4Q42reIhMOhhjCpHuJDIKlN8CZ1/z2ID9VZkNqi6X9r7TqWHEPZccUS2hPnO5A5gjzrKGFyxDzd7DOZjYVxeOScWrN2t4KaN2Nzmx4iD7rXBt41F3i1oq/mVOsmSvQ7sgbUcwQ7cgdAcDFBmw1TNDeQfL6Q1UDAI+o8AXmN10ChsQwZsrvrt/qWdSD0Cde8tHihTd1qyQofrAMav8RJ3bnrgRrUVK86YZIaEDG7ubP8iuWLJkaW4LtnHvQqXyIP6TXNUpUnEcdNxplDwjp+ln8MbmYvLTJSB0CNbvs2OE5qblGXImGOW4ovDgy/PjWiRkhW0lfqvQDjcc04bKbcpM2qPrS7ruHg3Mjop2wTSOflp2E0VFaxwmT2DX1Eonxsgw4pHSFn9xCxDj0G8OfdsUEBiJ92M2QQPEjThPJdR9j3Ik5reGTXkxa5yI9FfS/RMOjZrPveHcwNcWRS0+qOv2Kfk5bo+Zh4oDdsfLdZmY5yRiFmItSAzOp2KAjITunjZtzb2kxl3HINy+q2kvph9wmHiMU646VErRpV5OEAgUtabtgTkIF+baFiu9JWHLxKbUgTyBxG7h9cw2l8SuwsK1ISktsWS6D+YvSgvtB6a//UCCcflhvNdq8=